LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

SingleSpaceBeforeFirstArg:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

DotPosition:
  EnforcedStyle: leading

AlignParameters:
  EnforcedStyle: with_fixed_indentation

IndentHash:
  EnforcedStyle: consistent

StringLiterals:
  EnforcedStyle: single_quotes

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'
