sudo: false
cache: bundler
language: ruby

# Ensure we don't build for *every* commit (doesn't apply to PR builds)
branches:
  only:
  - master

script:
  - cp config/application.yml.sample config/application.yml
  - bundle exec rspec --format documentation
